# deploy config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giotto-gateway-core
spec:
  replicas: 3
  selector:
    matchLabels:
      name: giotto-gateway-core
  template:
    metadata:
      labels:
        name: giotto-gateway-core
    spec:
      containers:
        - name: giotto-gateway-core
          image: giotto-gateway-core:d1785da
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
---
# service config
apiVersion: v1
kind: Service
metadata:
  name: giotto-gateway-core
spec:
  ports:
    - port: 80
      name: "http-proxy"
      targetPort: 80
      protocol: TCP
      nodePort: 30080
    - port: 443
      name: "https-proxy"
      targetPort: 443
      protocol: TCP
      nodePort: 30443
  type: NodePort
  selector:
    name: giotto-gateway-core